set_names = {"jack", "james", "kate", "ben", "jin", "sun"}  # set: un-ordered, unique
list_names = ["jack", "james", "kate", "ben", "jin", "sun"]  # list: ordered, duplicate
print(set_names)
print(len(set_names))
set_names.add("james")
set_names.add("james")
set_names.add("jack")
set_names.add("jin")
set_names.add("sun")
print(set_names)
print(len(set_names))
list_names.append("james")
list_names.append("james")
list_names.append("jack")
list_names.append("jin")
list_names.append("sun")
print(list_names)
print(len(list_names))
list_names.sort()
print(list_names)
sorted_set_names = sorted(set_names)
print(sorted_set_names)
print("jack" in set_names)
print("jack" in list_names)
list_names.remove("jack")
del list_names[0]