# -*- coding: utf-8 -*-
"""module01-pyton.basics-2023.sep.26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10L3TVze5I7AZLVgrKkkTeDFClNB0PqYw
"""

age = 42

type(age)

print(age)

age = "kate austen"

type(age)

age = 3.141516171819

type(age)

age = 2+2 == 4

type(age)

age

salary = None

type(salary)

type(3. * 2)

type(3 * 2)

type(4 / 2)

type(3 / 2)

4/2



3 // 2

type(3 // 2)

1 / 0

1 // 0

0 / 0

x = float('inf')

x

x = float('-inf')

x

x = float('NaN')

x = x // 2

x

x == float("NaN")

x == x

import math

math.isnan(x)

x = float('-inf')
math.isinf(x)

x = 42
math.isfinite(x)

money = 2.0
money = money - 1.10
money

x = ( 0.1 + 0.2 ) + 0.3
y = 0.1 + ( 0.2 + 0.3 )
x == y

z = 100 * 4.35
z

(0.1+0.2) + 0.3

0.1 + 0.2

0.1 + (0.2 + 0.3)

from mpmath import *

mp.dps = 100_000
mp.pretty = True

my_pi = 4 * atan(1)

print(my_pi)

u = 2**10000
print(u)
print(type(u))

x = 3.1415
print(type(x))

z = 2+2 == 4
print(type(z))

fullname = 'jack bauer'
print(type(fullname))

3 // 2

math.floor( 3 * 1.4)

math.ceil( 3 * 1.4)

int("42")

int(42.99999)

int("forty two")

float("3.1415")

float(2 * 2)

float("four point two")

float("nan")

float("inf")

bool("true")

bool("dfgdgf")

fullname = "Jack Bauer" # immutable class

print(type(fullname))

print(fullname)

print(len(fullname))

fullname = fullname.lower()

fullname.replace('a', 'A')

fullname

x = "\u20ba"
print(x)

x = b"\xf0\x9d\x84\x9e"

print(type(x))

print(x)

y = x.decode("utf-8")

y

len(y)

len(x)

x = "jack"
y = "jack"
z = "jack"

z.upper()