fullname = "hugo reyes"
print(fullname[0])
print(fullname[1])
print(fullname[2])
print(fullname[-1])
print(fullname[-2])
print(fullname[-3])
print(len(fullname))
print(fullname[-10])
# IndexError: print(fullname[-11])
# IndexError: print(fullname[10])
print(fullname[2:6:1])
print(fullname[:3])
print(fullname[::-1])
print(fullname[0::2])
